FROM linuxserver/rdesktop:ubuntu-xfce

# Update repositories
RUN apt-get update -y

# Utilities
RUN apt-get install -y nano
RUN apt-get install -y git
RUN apt-get install -y iputils-ping iproute2 nmap
